version: 2.1
jobs:
  build:
    docker: 
      - image: loadimpact/k6:0.25.1
    steps:
      - checkout
      - run:
          name: Run load test
          command: k6 run -q -o cloud loadtests/main.js
