version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run: pwd
      - run: ls -lh
      - run:
          name: Download k6 image
          command: docker pull loadimpact/k6:0.25.1
      - run:
          name: Run load test
          command: docker run -i -e K6_CLOUD_TOKEN=$K6_CLOUD_TOKEN loadimpact/k6:0.25.1 run -q -e PROJECT_ID=3071449 -o cloud - <loadtests/main.js
      #- run:
      #    name: Run load test
      #    command: docker run -i -e K6_CLOUD_TOKEN=$K6_CLOUD_TOKEN -v /home/circleci/project:/k6 loadimpact/k6:0.25.1 run -q -o cloud /k6/loadtests/main.js
